// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhkcokbkksbfqtctjjkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoa2Nva2Jra3NiZnF0Y3Rqamt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjI1MDksImV4cCI6MjA2MzEzODUwOX0._u6ZDxtqsC8M8RpwiOgozYeUhO4eN6sJWkWLkzbwa3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);