// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtsfvbvgnbxtulcgxfkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0c2Z2YnZnbmJ4dHVsY2d4Zmt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NzMwMjQsImV4cCI6MjA2MTQ0OTAyNH0.zP7rny4qfJ5-Ntcz3_um64ZKJR0ROyzM-IlxQvaAf0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);